#!/usr/bin/env perl

use strict;
use warnings;
use FindBin qw($Bin);
use lib "$Bin/../lib";

use D2TG::Config;
use D2TG::Telegram;
use D2TG::Poller;

exit 1 unless D2TG::Config::require_chat_id_or_warn();

print "d2tg poller starting up (token set: "
    . ( defined D2TG::Config::token() ? "yes" : "no" ) . ")\n";

my $shutting_down = 0;
$SIG{TERM} = sub { $shutting_down = 1 };
$SIG{INT}  = sub { $shutting_down = 1 };

my $telegram = D2TG::Telegram->new( token => D2TG::Config::token() );
my $offset;

until ($shutting_down) {
    ( undef, $offset ) = D2TG::Poller::run_once( $telegram, $offset );
}

exit 0;

=head1 NAME

poller - tg skill entrypoint, dispatched as C<d2 tg.poller>

=head1 DESCRIPTION

Calls L<D2TG::Config>'s startup guard first and refuses to proceed
(non-zero exit, nothing on STDOUT) when C<D2TG_CHAT_ID> is missing. Once
the guard passes, runs L<D2TG::Poller>'s long-poll loop until C<SIGTERM>
or C<SIGINT> is received. There is no access control yet - every sender's
text message reaches STDOUT (see L<D2TG::Poller>).

=cut
